version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "=================================================================[*] Login ECR================================================================="
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_ACCOUNT.dkr.ecr.$ECR_REGION.amazonaws.com/$PROJECT_NAME
  build:
    commands:
      - echo "=================================================================[*] Build & Dockerizing================================================================="
      - docker build -t $PROJECT_NAME .
      - docker tag $PROJECT_NAME $ECR_ACCOUNT.dkr.ecr.$ECR_REGION.amazonaws.com/$PROJECT_NAME:"$BRANCH_NAME"
      - docker push $ECR_ACCOUNT.dkr.ecr.$ECR_REGION.amazonaws.com/$PROJECT_NAME:"$BRANCH_NAME"